[database]
db_type = 'postgresql'
host = 'pgm-bp1891c4448of47amo.rwlb.rds.aliyuncs.com'
password = 'j2OR4rrFHt@8'
user = 'omoptest'
port = 5432
db = 'dms'
engine_options = { echo = false }
table_schemas = { task = 'dms', group = 'dms' }
table_names = { task = 'dms_celery_tasks', group = 'dms_celery_groups' }

[redis]
type = 'standalone'
hosts = [
    { host = '120.27.20.10', port = 6379 }
]
db = 12
password = 'q10tPO4yfQWYqku2'
transport_options = { max_retries = 3, interval_start = 2, interval_step = 0.2, interval_max = 0.2 }
connection_retry_on_startup = true


[storage]
host = 's3.amazonaws.com'
port = 443
access_key = 'AKIAQQ3OKMH6W5RQFHFJ'
secret_key = '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'
secure = true
bucket_name = 'dms-us-east2'
region = 'us-east-2'

[main]
tmp_pdf_path = '/Library/app/nyquistdata/pdf-ocr-service/tmp'
app_name = 'pdf-ocr-service'
default_language = 'eng'

[dms-service]
schema = 'http'
host = 'localhost'
port = 8001
path = '/dms/callback/process'
method = 'POST'
headers = { x-api-key = 'xxxxx', Content-Type = 'application/json' }

[celery]
worker_prefetch_multiplier = 1
worker_concurrency = 1
accept_content = ["application/json"]
result_serializer = 'json'
task_imports = ["pdf_ocr_service.jobs.tasks", ]
worker_log_format = '[%(asctime)s: %(levelname)s/%(processName)s] %(message)s'
task_log_format = '[%(asctime)s: %(levelname)s/%(processName)s] %(task_name)s[%(task_id)s]: %(message)s'
timezone = 'utc-8'
enable_utc = true

[logger]
worker_config = { max_bytes = 10485760, backup_count = 7, log_level = "INFO" , log_file='/Library/app/nyquistdata/pdf-ocr-service/logs/worker.log'}
task_config = { maxBytes = 104857600, backupCount = 7, log_level = "INFO",log_file='/Library/app/nyquistdata/pdf-ocr-service/logs/tasks.log' }




[tasks]
queues = { pdf_ocr = { exchange = 'pdf_ocr', routing_key = 'routing_key' }, image_extractor = { exchange = 'image_extractor', routing_key = 'routing_key' }, office_extractor = { exchange = 'office_extractor', routing_key = 'routing_key' }, pdf_extractor = { exchange = 'pdf_extractor', routing_key = 'routing_key' } }
routes = [{ task = 'pdf_ocr_service.jobs.tasks.ocr_pdf_document', route = { queue = 'pdf_ocr', exchange = 'direct', serializer = 'serializer', routing_key = 'pdf_ocr_service.jobs.tasks.ocr_pdf_document' } },
    { task = 'pdf_ocr_service.jobs.tasks.extract_office_document', route = { queue = 'office_extractor', exchange = 'direct', serializer = 'serializer', routing_key = 'pdf_ocr_service.jobs.tasks.extract_office_document' } },
    { task = 'pdf_ocr_service.jobs.tasks.identify_image_document', route = { queue = 'image_extractor', exchange = 'direct', serializer = 'serializer', routing_key = 'pdf_ocr_service.jobs.tasks.identify_image_document' } },
    { task = 'pdf_ocr_service.jobs.tasks.extract_pdf_document', route = { queue = 'pdf_extractor', exchange = 'direct', serializer = 'serializer', routing_key = 'pdf_ocr_service.jobs.tasks.extract_pdf_document' } }
]
acks_on_failure_or_timeout = false
default_routing_key = 'pdf_ocr_service'
default_exchange = 'pdf_ocr_service'
default_exchange_type = 'direct'

[ai]
access_key = 'AKIAQQ3OKMH6SHUGE23N'
secret_key = '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'
service_name = 'bedrock-runtime'
region_name = 'us-west-2'
accept = 'application/json'
content_type = 'application/json'
embedding = { model_id = 'cohere.embed-multilingual-v3', input_type = 'search_document' }
summary = { model_id = 'anthropic.claude-v2', max_tokens_to_sample = 1024, temperature = 0.1, stop_sequences = [] }